/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'error-dim': 'var(--color-error-dim)',
        'on-background': 'var(--color-on-background)',
        'primary-dim': 'var(--color-primary-dim)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-variant)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'on-primary-fixed': 'var(--color-on-primary)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'on-secondary-fixed': 'var(--color-on-secondary)',
        'secondary': 'var(--color-secondary)',
        'surface': 'var(--color-surface)',
        'outline': 'var(--color-outline)',
        'error-container': 'var(--color-error-container)',
        'surface-dim': 'var(--color-surface-dim)',
        'tertiary-fixed': 'var(--color-tertiary-container)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        'on-secondary': 'var(--color-on-secondary)',
        'secondary-dim': 'var(--color-secondary-dim)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'on-tertiary-fixed': 'var(--color-on-tertiary)',
        'surface-container': 'var(--color-surface-container)',
        'on-tertiary': 'var(--color-on-tertiary)',
        'secondary-fixed': 'var(--color-secondary-container)',
        'on-primary-fixed-variant': 'var(--color-on-primary-container)',
        'inverse-surface': 'var(--color-inverse-surface)',
        'inverse-primary': 'var(--color-inverse-primary)',
        'surface-variant': 'var(--color-surface-variant)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'background': 'var(--color-background)',
        'primary-fixed-dim': 'var(--color-primary-dim)',
        'on-surface': 'var(--color-on-surface)',
        'tertiary-dim': 'var(--color-tertiary-dim)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-container)',
        'outline-variant': 'var(--color-outline-variant)',
        'secondary-fixed-dim': 'var(--color-secondary-dim)',
        'primary': 'var(--color-primary)',
        'inverse-on-surface': 'var(--color-inverse-on-surface)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'primary-container': 'var(--color-primary-container)',
        'on-error': 'var(--color-on-error)',
        'error': 'var(--color-error)',
        'on-error-container': 'var(--color-on-error-container)',
        'tertiary': 'var(--color-tertiary)',
        'secondary-container': 'var(--color-secondary-container)',
        'primary-fixed': 'var(--color-primary)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        'tertiary-fixed-dim': 'var(--color-tertiary-dim)',
        'on-primary': 'var(--color-on-primary)',
        'surface-tint': 'var(--color-primary)',
        'surface-bright': 'var(--color-surface-bright)'
      },
      fontFamily: {
        'headline': ['Plus Jakarta Sans', 'Noto Sans SC', 'sans-serif'],
        'body': ['Inter', 'Noto Sans SC', 'sans-serif'],
        'label': ['Inter', 'Noto Sans SC', 'sans-serif'],
        'mono': ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'Liberation Mono', 'Courier New', 'monospace']
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
        'sm': '0.125rem',
        'md': '0.375rem'
      },
      boxShadow: {
        'ambient': '0 16px 48px var(--shadow-soft)',
        'sticky-up': '0 -8px 24px var(--shadow-soft)',
      }
    },
  },
  plugins: [],
}
